import React, { createContext, useContext, useState, useCallback, ReactNode } from 'react';

type Language = 'es' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
  toggleLanguage: () => void;
}

const translations: Record<Language, Record<string, any>> = {
  es: {
    "nav.inicio": "Inicio",
    "nav.sectores": "Sectores",
    "nav.productos": "Productos",
    "nav.instalaciones": "Instalaciones",
    "nav.calidad": "Calidad",
    "nav.contacto": "Contacto",
    "hero.badge": "Tecnología de envasado",
    "hero.title": "Más de 35 años de experiencia",
    "hero.titleHighlight": "como Co-Packer de marcas líderes a nivel mundial",
    "hero.subtitle": "Infraestructura única en España con capacidad de fabricación y envasado bajo las más estrictas normativas sanitarias, cosméticas y alimentarias.",
    "hero.ctaPrimary": "Descubre nuestras instalaciones",
    "hero.ctaSecondary": "Contactar",
    "hero.stats.lines": "Líneas de Producción",
    "hero.stats.cleanrooms": "Salas Blancas",
    "hero.stats.experience": "Años de Experiencia",
    "hero.stats.capacity": "Unidades/año",
    "sectores.title": "Sectores",
    "sectores.subtitle": "Especialización por tipo de industria",
    "sectores.cosmetic.title": "Cosmética, Higiene y Perfumería",
    "sectores.cosmetic.description": "Socio estratégico de las firmas más prestigiosas del sector. Especialistas en el envasado de fragancias de lujo y cosmética de alta gama para marcas líderes a nivel mundial.",
    "sectores.cosmetic.features": ["Líneas dedicadas de alta precisión", "Control de calidad y control de proceso continuo", "Gestión de componentes de lujo"],
    "sectores.sanitary.title": "Productos Sanitarios",
    "sectores.sanitary.description": "Infraestructura especializada para el sector salud. Cumplimiento estricto de normativas internacionales para productos sanitarios.\nÁrea de fabricación y de envasado estéril.",
    "sectores.sanitary.features": ["7 Salas blancas certificadas", "Planta de agua purificada propia con capacidad de 700 L/h", "Control microbiológico continuo"],
    "sectores.food.title": "Alimentación",
    "sectores.food.description": "Soluciones avanzadas para la industria alimentaria, con salas específicas para productos sensibles que requieren control ambiental riguroso.",
    "sectores.food.features": ["Salas climatizadas y con control de humedad activo", "Trazabilidad completa", "Certificaciones alimentarias internacionales"],
    "copacker.subtitle": "Co-Packer",
    "copacker.title": "Packaging a su medida",
    "copacker.description": "Trabajamos mano a mano con nuestros clientes para ofrecerle soluciones enteramente personalizadas",
    "copacker.cta.tech": "Nuestra tecnología",
    "copacker.cta.policy": "Política de gestión",
    "copacker.feature1": "Capacidad",
    "copacker.feature1.desc": "Actualmente somos una de las empresas con mayor capacidad de envasado a terceros de Europa.",
    "copacker.feature2": "Tecnología",
    "copacker.feature2.desc": "Disponemos de maquinaria de última generación para garantizar la máxima precisión en cada envase.",
    "copacker.feature3": "Líneas de envasado",
    "copacker.feature3.desc": "30 líneas de envasado de diferente tipologías para adaptarnos a diferentes formatos y sectores",
    "copacker.feature4": "Personalización",
    "copacker.feature4.desc": "Trabajamos mano a mano con nuestros clientes para ofrecer soluciones enteramente personalizadas.",
    "productos.title": "Productos",
    "productos.subtitle": "Soluciones de packaging para cada necesidad",
    "productos.items.sachets.title": "Sachets & Toallitas",
    "productos.items.sachets.description": "Formato ideal para retail y sampling. Económico, versátil, personalizable y eco-friendly.",
    "productos.items.sachets.capacity": "0,1 ML - 100 ML",
    "productos.items.bottles.title": "Frascos",
    "productos.items.bottles.description": "El envase estándar más versátil. Sin limitaciones de formato, capacidad o cierre.",
    "productos.items.bottles.capacity": "0,5 ML - 1 LITRO",
    "productos.items.jars.title": "Tarros y Tarrinas",
    "productos.items.jars.description": "Versatilidad máxima para cosmética y alimentación. Amplia gama de capacidades y acabados.",
    "productos.items.jars.capacity": "5 ML - 500 ML",
    "productos.items.vials.title": "Viales",
    "productos.items.vials.description": "Formato premium para cosmética y farmacia. Gran variedad de cierres especializados.",
    "productos.items.vials.capacity": "1 ML - 30 ML",
    "instalaciones.title": "Instalaciones",
    "instalaciones.subtitle": "Infraestructura de vanguardia para producción a escala",
    "instalaciones.manufacturing.title": "Zona de Fabricación",
    "instalaciones.manufacturing.description": "Capacidad de fabricación propia además de envasado. Control total del proceso productivo.",
    "instalaciones.cleanrooms.title": "7 Salas Blancas",
    "instalaciones.cleanrooms.description": "Cualificadas para productos sanitarios con control de partículas y microbiológico.",
    "instalaciones.food.title": "6 Food Rooms",
    "instalaciones.food.description": "Especializadas para productos alimentarios, 2 con control de humedad activo.",
    "instalaciones.sterile.title": "Sala de Envasado Estéril",
    "instalaciones.sterile.description": "Ambiente controlado para productos que requieren condiciones asépticas.",
    "instalaciones.water.title": "Planta de Agua Purificada",
    "instalaciones.water.description": "Capacidad de 700 L/h para procesos de fabricación y limpieza.",
    "instalaciones.warehouse.title": "Raw Materials Warehouse",
    "instalaciones.warehouse.description": "Gestión integral de componentes y materiales con traza completa.",
    "instalaciones.stats.lines": "Líneas de Producción",
    "instalaciones.stats.cleanrooms": "Salas Blancas",
    "instalaciones.stats.water": "L/h Agua Purificada",
    "instalaciones.stats.storage": "m² Almacén",
    "calidad.title": "Calidad",
    "calidad.subtitle": "Certificaciones y reconocimientos internacionales",
    "calidad.iso.title": "ISO 9001:2015",
    "calidad.iso.description": "Sistema de gestión de calidad certificado para garantizar procesos optimizados y resultados consistentes.",
    "calidad.gmp.title": "BPF / GMP",
    "calidad.gmp.description": "Cumplimiento de Buenas Prácticas de Fabricación para productos sanitarios y cosméticos.",
    "calidad.process.title": "Control de Calidad",
    "calidad.process.description": "Procesos rigurosos de control en cada etapa de producción, desde la recepción de materias primas hasta el producto final.",
    "calidad.process.points": ["Inspección visual 100% de productos acabados", "Control dimensional preciso", "Verificación de sellados y cierres", "Análisis microbiológico cuando es requerido"],
    "contacto.title": "Contacto",
    "contacto.subtitle": "Hablemos de tu próximo proyecto",
    "contacto.form.name": "Nombre",
    "contacto.form.email": "Email",
    "contacto.form.company": "Empresa",
    "contacto.form.phone": "Teléfono",
    "contacto.form.message": "Mensaje",
    "contacto.form.submit": "Enviar mensaje",
    "contacto.form.success": "Mensaje enviado correctamente",
    "contacto.info.address": "Dirección",
    "contacto.info.phone": "Teléfono",
    "contacto.info.email": "Email",
    "contacto.info.schedule": "Horario",
    "contacto.company.name": "Central de Envasados, S.A.",
    "contacto.company.address": "Polígono Industrial La Garena Sur, Miguel Servet, 10, 28806 Alcalá de Henares (Madrid)",
    "contacto.company.phone": "918 811 415",
    "contacto.company.email": "contacto@centralenvasados.com",
    "contacto.company.schedule": "Lunes a Viernes: 8:00 - 17:00",
    "footer.legalNotice": "De conformidad con lo que dispone el Reglamento (UE) 2016/679 de 27 de abril de 2016 (RGPD), la Ley Orgánica 3/2018 del 5 de diciembre (LOPDGDD) y demás normativa legal vigente en materia de protección de datos personales, le informamos que los datos personales aportados en este formulario de contacto serán tratados por Central de Envasados, S.A con la finalidad de obtener el catálogo seleccionado así como gestionar sus datos previo consentimiento para el envío de información comercial. La legitimación para el tratamiento de sus datos personales se basa en el consentimiento del interesado. Sus datos se conservarán durante el tiempo necesario para cumplir con la finalidad para la que se recabaron y para determinar las posibles responsabilidades que se pudieran derivar de dicha finalidad y del tratamiento de los datos. No se realizan transferencias internacionales de datos, perfilados ni sometimiento de datos a decisiones automatizadas. Podrá ejercitar sus derechos de acceso, rectificación, oposición, supresión, limitación del tratamiento y portabilidad dirigiéndose por escrito y con acreditación de su identidad ante Central de Envasados, S.A en la dirección de correo info@centraldeenvasados.com Tiene derecho a interponer una reclamación ante la autoridad de control si considera que sus derechos no han sido correctamente atendidos, dirigiéndose a la Agencia Española de Protección de Datos (www.aepd.es).",
    "footer.rights": "Todos los derechos reservados",
    "footer.legal": "Aviso Legal",
    "footer.privacy": "Política de Privacidad",
    "footer.cookies": "Cookies"
  },
  en: {
    "nav.inicio": "Home",
    "nav.sectores": "Sectors",
    "nav.productos": "Products",
    "nav.instalaciones": "Facilities",
    "nav.calidad": "Quality",
    "nav.contacto": "Contact",
    "hero.badge": "Packaging Technology",
    "hero.title": "Over 35 years of experience",
    "hero.titleHighlight": "as a Co-Packer for world-leading brands",
    "hero.subtitle": "Unique infrastructure in Spain with manufacturing and packaging capacity under the strictest sanitary, cosmetic, and food regulations.",
    "hero.ctaPrimary": "Discover our facilities",
    "hero.ctaSecondary": "Contact us",
    "hero.stats.lines": "Production Lines",
    "hero.stats.cleanrooms": "Clean Rooms",
    "hero.stats.experience": "Years of Experience",
    "hero.stats.capacity": "Units/year",
    "sectores.title": "Sectors",
    "sectores.subtitle": "Specialization by industry",
    "sectores.cosmetic.title": "Cosmetics, Hygiene & Perfumery",
    "sectores.cosmetic.description": "Strategic partner for the most prestigious firms in the sector. Specialists in packaging luxury fragrances and high-end cosmetics for world-leading brands.",
    "sectores.cosmetic.features": ["High-precision dedicated lines", "Quality control and continuous process monitoring", "Luxury component management"],
    "sectores.sanitary.title": "Sanitary Products",
    "sectores.sanitary.description": "Specialized infrastructure for the health sector. Strict compliance with international regulations for sanitary products.\nManufacturing area and sterile packaging.",
    "sectores.sanitary.features": ["7 Certified clean rooms", "Own purified water plant with 700 L/h capacity", "Continuous microbiological control"],
    "sectores.food.title": "Food",
    "sectores.food.description": "Advanced solutions for the food industry, with specific rooms for sensitive products requiring rigorous environmental control.",
    "sectores.food.features": ["Climate-controlled rooms with active humidity control", "Full traceability", "International food certifications"],
    "copacker.subtitle": "Co-Packer",
    "copacker.title": "Tailor-made Packaging",
    "copacker.description": "We work hand in hand with our clients to offer entirely personalized solutions",
    "copacker.cta.tech": "Our Technology",
    "copacker.cta.policy": "Management Policy",
    "copacker.feature1": "Capacity",
    "copacker.feature1.desc": "We are currently one of the companies with the highest third-party packaging capacity in Europe.",
    "copacker.feature2": "Technology",
    "copacker.feature2.desc": "We have state-of-the-art machinery to guarantee maximum precision in every package.",
    "copacker.feature3": "Packaging Lines",
    "copacker.feature3.desc": "30 packaging lines of different typologies to adapt to different formats and sectors",
    "copacker.feature4": "Customization",
    "copacker.feature4.desc": "We work hand in hand with our clients to offer entirely personalized solutions.",
    "productos.title": "Products",
    "productos.subtitle": "Packaging solutions for every need",
    "productos.items.sachets.title": "Sachets & Wipes",
    "productos.items.sachets.description": "Ideal format for retail and sampling. Economical, versatile, customizable, and eco-friendly.",
    "productos.items.sachets.capacity": "0.1 ML - 100 ML",
    "productos.items.bottles.title": "Bottles",
    "productos.items.bottles.description": "The most versatile standard format. No limitations on format, capacity, or closure.",
    "productos.items.bottles.capacity": "0.5 ML - 1 LITER",
    "productos.items.jars.title": "Jars and Tubs",
    "productos.items.jars.description": "Maximum versatility for cosmetics and food. Wide range of capacities and finishes.",
    "productos.items.jars.capacity": "5 ML - 500 ML",
    "productos.items.vials.title": "Vials",
    "productos.items.vials.description": "Premium format for cosmetics and pharmacy. Wide variety of specialized closures.",
    "productos.items.vials.capacity": "1 ML - 30 ML",
    "instalaciones.title": "Facilities",
    "instalaciones.subtitle": "Cutting-edge infrastructure for large-scale production",
    "instalaciones.manufacturing.title": "Manufacturing Zone",
    "instalaciones.manufacturing.description": "Own manufacturing capacity in addition to packaging. Total control of the production process.",
    "instalaciones.cleanrooms.title": "7 Clean Rooms",
    "instalaciones.cleanrooms.description": "Qualified for sanitary products with particle and microbiological control.",
    "instalaciones.food.title": "6 Food Rooms",
    "instalaciones.food.description": "Specialized for food products, 2 with active humidity control.",
    "instalaciones.sterile.title": "Sterile Packaging Room",
    "instalaciones.sterile.description": "Controlled environment for products requiring aseptic conditions.",
    "instalaciones.water.title": "Purified Water Plant",
    "instalaciones.water.description": "700 L/h capacity for manufacturing processes and cleaning.",
    "instalaciones.warehouse.title": "Raw Materials Warehouse",
    "instalaciones.warehouse.description": "Comprehensive component and material management with complete traceability.",
    "instalaciones.stats.lines": "Production Lines",
    "instalaciones.stats.cleanrooms": "Clean Rooms",
    "instalaciones.stats.water": "L/h Purified Water",
    "instalaciones.stats.storage": "m² Warehouse",
    "calidad.title": "Quality",
    "calidad.subtitle": "International certifications and recognitions",
    "calidad.iso.title": "ISO 9001:2015",
    "calidad.iso.description": "Certified quality management system to ensure optimized processes and consistent results.",
    "calidad.gmp.title": "GMP",
    "calidad.gmp.description": "Compliance with Good Manufacturing Practices for sanitary and cosmetic products.",
    "calidad.process.title": "Quality Control",
    "calidad.process.description": "Rigorous control processes at every stage of production, from raw material reception to finished product.",
    "calidad.process.points": ["100% visual inspection of finished products", "Precise dimensional control", "Seal and closure verification", "Microbiological analysis when required"],
    "contacto.title": "Contact",
    "contacto.subtitle": "Let's talk about your next project",
    "contacto.form.name": "Name",
    "contacto.form.email": "Email",
    "contacto.form.company": "Company",
    "contacto.form.phone": "Phone",
    "contacto.form.message": "Message",
    "contacto.form.submit": "Send message",
    "contacto.form.success": "Message sent successfully",
    "contacto.info.address": "Address",
    "contacto.info.phone": "Phone",
    "contacto.info.email": "Email",
    "contacto.info.schedule": "Schedule",
    "contacto.company.name": "Central de Envasados, S.A.",
    "contacto.company.address": "Polígono Industrial La Garena Sur, Miguel Servet, 10, 28806 Alcalá de Henares (Madrid)",
    "contacto.company.phone": "918 811 415",
    "contacto.company.email": "contacto@centralenvasados.com",
    "contacto.company.schedule": "Monday to Friday: 8:00 - 17:00",
    "footer.legalNotice": "In accordance with the provisions of Regulation (EU) 2016/679 of April 27, 2016 (GDPR), Organic Law 3/2018 of December 5 (LOPDGDD) and other current legal regulations on the protection of personal data, we inform you that the personal data provided in this contact form will be processed by Central de Envasados, S.A for the purpose of obtaining the selected catalog as well as managing your data with prior consent for the sending of commercial information. The legitimation for the processing of your personal data is based on the consent of the data subject. Your data will be kept for the time necessary to fulfill the purpose for which they were collected and to determine the possible responsibilities that could derive from said purpose and the processing of the data. No international data transfers, profiling or submission of data to automated decisions are carried out. You may exercise your rights of access, rectification, opposition, deletion, limitation of processing and portability by writing and with accreditation of your identity to Central de Envasados, S.A at the email address info@centraldeenvasados.com You have the right to file a claim with the control authority if you consider that your rights have not been correctly addressed, by contacting the Spanish Data Protection Agency (www.aepd.es).",
    "footer.rights": "All rights reserved",
    "footer.legal": "Legal Notice",
    "footer.privacy": "Privacy Policy",
    "footer.cookies": "Cookies"
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('es');

  const t = useCallback((key: string) => {
    return translations[language][key] || key;
  }, [language]);

  const toggleLanguage = useCallback(() => {
    setLanguage(prev => prev === 'es' ? 'en' : 'es');
  }, []);

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, toggleLanguage }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
