import React, { createContext, useContext, useState, useCallback, ReactNode } from 'react';

type Language = 'es' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
  toggleLanguage: () => void;
}

const translations: Record<Language, Record<string, any>> = {
  es: {
    "nav.inicio": "Inicio",
    "nav.nosotros": "Nosotros",
    "nav.sectores": "Sectores",
    "nav.productos": "Productos",
    "nav.instalaciones": "Instalaciones",
    "nav.calidad": "Calidad",
    "nav.contacto": "Contacto",
    "hero.badge": "Líder Europeo en Co-Packing",
    "hero.title": "Más de 35 años de experiencia",
    "hero.titleHighlight": "como Co‑Packer de marcas líderes a nivel mundial",
    "hero.subtitle": "Infraestructura única en España con capacidad de fabricación y envasado bajo las más estrictas normativas sanitarias, cosméticas y alimentarias.",
    "hero.ctaPrimary": "Descubre nuestras instalaciones",
    "hero.ctaSecondary": "Contactar",
    "hero.stats.lines": "Líneas de Producción",
    "hero.stats.cleanrooms": "Salas Blancas",
    "hero.stats.talent": "Profesionales",
    "hero.stats.experience": "Años de Experiencia",
    "hero.stats.capacity": "Unidades/año",
    "nosotros.title": "Nuestra Historia: El Compromiso con nuestros Clientes",
    "nosotros.subtitle": "Más de 35 años evolucionando con la calidad como objetivo",
    "nosotros.p1": "Fundada hace más de tres décadas como un proyecto familiar, Central de Envasados ha recorrido un camino de crecimiento constante y reinversión tecnológica. Lo que comenzó como una visión local se ha transformado hoy en un referente europeo del co-packing de alta capacidad.",
    "nosotros.p2": "Esta evolución, basada en la reinversión continua y la retención del talento, nos ha permitido escalar sin perder nuestra esencia: más de 250 profesionales especializados gestionan diariamente operaciones críticas desde nuestras mas de 30 salas de envasado, 6 salas blancas certificadas y una sala de envasado estéril, además de nuestra propia planta de agua purificada para la fabricación de productos sanitarios y cosméticos.",
    "nosotros.p3": "Hoy, esa misma esencia familiar —atención al detalle, trato personalizado— convive con el rigor industrial que exigen las firmas cosméticas y farmacéuticas más prestigiosas del mundo, somos el socio invisible que garantiza que su calidad llegue intacta al cliente final. Esa es nuestra historia: crecer sin olvidar que, al final, cada envase lleva el nombre de alguien que confía en nosotros.",
    "nosotros.cta": "Conoce a nuestro equipo",
    "nosotros.stat1": "Crecimiento Sostenido",
    "nosotros.stat2": "Talento Especializado",
    "nosotros.stat3": "Inversión en Tecnología",
    "sectores.title": "Sectores",
    "sectores.subtitle": "Especialización por tipo de industria",
    "sectores.cosmetic.title": "Cosmética, Higiene y Perfumería",
    "sectores.cosmetic.description": "Socio estratégico de las firmas más prestigiosas del sector. Especialistas en el envasado de fragancias de lujo y cosmética de alta gama para marcas líderes a nivel mundial.",
    "sectores.cosmetic.features": ["Líneas dedicadas de alta precisión", "Control de calidad y control de proceso continuo", "Gestión de componentes de lujo"],
    "sectores.sanitary.title": "Productos Sanitarios",
    "sectores.sanitary.description": "Infraestructura especializada para el sector salud. Cumplimiento estricto de normativas internacionales para productos sanitarios.\nÁrea de fabricación y de envasado estéril.",
    "sectores.sanitary.features": ["6 Salas blancas certificadas + 1 Sala Envasado Estéril", "Planta de agua purificada propia con capacidad de 700 L/h", "Control microbiológico continuo"],
    "sectores.food.title": "Alimentación",
    "sectores.food.description": "Soluciones avanzadas para la industria alimentaria, con salas específicas para productos sensibles que requieren control ambiental riguroso.",
    "sectores.food.features": ["Salas climatizadas y con control de humedad activo", "Trazabilidad completa", "Certificaciones alimentarias internacionales"],
    "copacker.subtitle": "CO-PACKER - FULL SERVICE",
    "copacker.title": "Packaging a su Medida - Proyectos 360º",
    "copacker.description": "En Central de Envasados no somos solo un co-packer; somos su socio integral en la materialización de proyectos, eliminando riesgos y gestionando cada fase.",
    "copacker.cta.tech": "Nuestra tecnología",
    "copacker.cta.policy": "Política de gestión",
    "copacker.feature1": "01. Infraestructura Industrial",
    "copacker.feature1.desc": "Capacidad productiva escalable: Operamos entre las mayores capacidades de envasado a terceros de Europa, con 30 líneas dedicadas funcionando simultáneamente. Esta escala nos permite absorber picos de demanda estacional y mantener tiempos de respuesta competitivos sin comprometer la calidad.",
    "copacker.feature2": "02. Versatilidad Tecnológica",
    "copacker.feature2.desc": "Multi-formato, multi-sector: Disponemos de 30 tecnologías de envasado diferenciadas (líneas rotativas, lineales, flow-pack, etiquetado, etc.) que nos permiten pivotar entre formatos cosméticos, sanitarios y alimentarios sin transición crítica. Una misma infraestructura, infinitas configuraciones.",
    "copacker.feature3": "03. Entorno Controlado",
    "copacker.feature3.desc": "Certificación y trazabilidad total: Fabricación en área sanitaria y envasado en 6 Salas Blancas certificadas y una Sala de Envasado Estéril, con planta de generación de agua purificada propia (700 L/h). Eliminamos riesgos de contaminación cruzada y garantizamos la trazabilidad batch desde la materia prima hasta el producto final.",
    "copacker.feature4": "04. Control de Calidad Integrado",
    "copacker.feature4.desc": "Cero defectos en línea: Sistema de inspección y control de proceso continuo, complementado con etiquetado de alta precisión y acondicionamiento secundario. Cada envase es verificado antes de abandonar la línea.",
    "copacker.feature5": "05. Gestión Integral de Packaging",
    "copacker.feature5.desc": "Full Service real: Diseño técnico y sourcing de envases, impresión gráfica industrial y gestión de packaging exterior con red de colaboradores auditados y certificados. Tú aportas la fórmula; nosotros gestionamos todo lo demás.",
    "copacker.feature6": "06. Partnership Operativo",
    "copacker.feature6.desc": "Tu proyecto, nuestro equipo: Asignación de equipos multidisciplinares dedicados por proyecto (IQ, Producción, Calidad) que trabajan en modalidad de extensión de tu departamento de operaciones, no como proveedor externo.",
    "productos.title": "Productos",
    "productos.subtitle": "Soluciones de packaging para cada necesidad",
    "productos.items.sachets.title": "Sachets & Toallitas",
    "productos.items.sachets.description": "Formato ideal para retail y sampling. Económico, versátil, personalizable y eco-friendly.",
    "productos.items.sachets.capacity": "0,1 ML - 100 ML",
    "productos.items.bottles.title": "Frascos",
    "productos.items.bottles.description": "El envase estándar más versátil. Sin limitaciones de formato, capacidad o cierre.",
    "productos.items.bottles.capacity": "0,5 ML - 1 LITRO",
    "productos.items.jars.title": "Tarros y Tarrinas",
    "productos.items.jars.description": "Versatilidad máxima para cosmética y alimentación. Amplia gama de capacidades y acabados.",
    "productos.items.jars.capacity": "5 ML - 500 ML",
    "productos.items.vials.title": "Viales",
    "productos.items.vials.description": "Formato premium para cosmética y farmacia. Gran variedad de cierres especializados.",
    "productos.items.vials.capacity": "1 ML - 30 ML",
    "instalaciones.title": "Instalaciones: Arquitectura de Grado Sanitario",
    "instalaciones.subtitle": "Capacidad Industrial Certificada",
    "instalaciones.manufacturing.title": "Fabricación de Grado Sanitario",
    "instalaciones.manufacturing.description": "Desarrollo de fórmulas críticas bajo protocolos asépticos y control digital total.",
    "instalaciones.cleanrooms.title": "6 Salas Blancas Certificadas",
    "instalaciones.cleanrooms.description": "Instalaciones cualificadas para productos sanitarios con control continuo de partículas y carga microbiológica.",
    "instalaciones.food.title": "6 Food Rooms Especializadas",
    "instalaciones.food.description": "Específicas para alimentación gourmet y nutraceúticos, con control de humedad activo.",
    "instalaciones.sterile.title": "Sala de Envasado Estéril",
    "instalaciones.sterile.description": "Área dedicada exclusivamente al envasado en condiciones asépticas estrictas (Sector Pharma).",
    "instalaciones.water.title": "Planta de Agua Purificada (700 L/h)",
    "instalaciones.water.description": "Garantía de calidad desde el origen. Suministro autónomo para fabricación y limpieza crítica.",
    "instalaciones.warehouse.title": "Logística con Trazabilidad Total",
    "instalaciones.warehouse.description": "Gestión integral de componentes con sistemas de validación de cada lote.",
    "instalaciones.stats.lines": "Líneas de Producción",
    "instalaciones.stats.cleanrooms": "Salas Blancas",
    "instalaciones.stats.water": "L/h Agua Purificada",
    "instalaciones.stats.storage": "m² Almacén",
    "calidad.title": "Rigor Normativo y Certificaciones 'Full Spectrum'",
    "calidad.subtitle": "Garantía de Confianza para Marcas Líderes",
    "calidad.iso.title": "ISO 9001:2015",
    "calidad.iso.description": "Sistema de gestión certificado para garantizar procesos optimizados y resultados consistentes.",
    "calidad.gmp.title": "BPF / GMP (ISO 22716)",
    "calidad.gmp.description": "Cumplimiento estricto de Buenas Prácticas de Fabricación para productos sanitarios y cosméticos.",
    "calidad.process.title": "Control de Calidad de Alta Precisión",
    "calidad.process.description": "Implementamos trazabilidad digital completa y validación clínica en cada fase, asegurando que cada unidad cumpla con los estándares de calidad requeridos.",
    "calidad.process.points": ["Validación microbiológica en laboratorio propio", "Inspección visual del 100% de productos acabados", "Trazabilidad digital completa de cada lote", "Control estricto de estabilidad y hermeticidad"],
    "contacto.title": "Contacto",
    "contacto.subtitle": "HABLEMOS DE TU PRÓXIMO PROYECTO",
    "contacto.form.name": "NOMBRE",
    "contacto.form.email": "EMAIL",
    "contacto.form.company": "EMPRESA",
    "contacto.form.phone": "TELÉFONO",
    "contacto.form.message": "MENSAJE",
    "contacto.form.submit": "ENVIAR MENSAJE",
    "contacto.form.success": "Mensaje enviado correctamente",
    "contacto.info.address": "DIRECCIÓN",
    "contacto.info.phone": "TELÉFONO",
    "contacto.info.email": "EMAIL",
    "contacto.info.schedule": "HORARIO",
    "contacto.company.name": "Central de Envasados, S.A.",
    "contacto.company.address": "Polígono Industrial La Garena Sur, Miguel Servet, 10, 28806 Alcalá de Henares (Madrid) ESPAÑA",
    "contacto.company.phone": "+34 918 811 415",
    "contacto.company.email": "contacto@centralenvasados.com",
    "contacto.company.schedule": "Lunes a Viernes: 8:00 - 17:00",
    "footer.description": "Partner estratégico de las principales marcas de cosmética, perfumería y cuidado personal. Más de 35 años de experiencia en fabricación y envasado de precisión.",
    "footer.sections.links": "ENLACES",
    "footer.sections.legal": "LEGAL",
    "footer.iso": "ISO 9001:2015 CERTIFIED",
    "footer.legalNotice": "De conformidad con lo que dispone el Reglamento (UE) 2016/679 de 27 de abril de 2016 (RGPD), la Ley Orgánica 3/2018 del 5 de diciembre (LOPDGDD) y demás normativa legal vigente en materia de protección de datos personales, le informamos que los datos personales aportados en este formulario de contacto serán tratados por Central de Envasados, S.A con la finalidad de obtener el catálogo seleccionado así como gestionar sus datos previo consentimiento para el envío de información comercial. La legitimación para el tratamiento de sus datos personales se basa en el consentimiento del interesado. Sus datos se conservarán durante el tiempo necesario para cumplir con la finalidad para la que se recabaron y para determinar las posibles responsabilidades que se pudieran derivar de dicha finalidad y del tratamiento de los datos. No se realizan transferencias internacionales de datos, perfilados ni sometimiento de datos a decisiones automatizadas. Podrá ejercitar sus derechos de acceso, rectificación, oposición, supresión, limitación del tratamiento y portabilidad dirigiéndose por escrito y con acreditación de su identidad ante Central de Envasados, S.A en la dirección de correo info@centraldeenvasados.com Tiene derecho a interponer una reclamación ante la autoridad de control si considera que sus derechos no han sido correctamente atendidos, dirigiéndose a la Agencia Española de Protección de Datos (www.aepd.es).",
    "footer.rights": "TODOS LOS DERECHOS RESERVADOS",
    "footer.legal": "Aviso Legal",
    "footer.privacy": "Política de Privacidad",
    "footer.cookies": "Cookies"
  },
  en: {
    "nav.inicio": "Home",
    "nav.nosotros": "About Us",
    "nav.sectores": "Sectors",
    "nav.productos": "Products",
    "nav.instalaciones": "Facilities",
    "nav.calidad": "Quality",
    "nav.contacto": "Contact",
    "hero.badge": "European Co-Packing Leader",
    "hero.title": "Over 35 years of experience",
    "hero.titleHighlight": "as a Co-Packer for world-leading brands",
    "hero.subtitle": "Unique infrastructure in Spain with manufacturing and packaging capacity under the strictest sanitary, cosmetic, and food regulations.",
    "hero.ctaPrimary": "Discover our facilities",
    "hero.ctaSecondary": "Contact us",
    "hero.stats.lines": "Production Lines",
    "hero.stats.cleanrooms": "Clean Rooms",
    "hero.stats.talent": "Specialized Personnel",
    "hero.stats.experience": "Years of Experience",
    "hero.stats.capacity": "Units/year",
    "nosotros.title": "Our History: Commitment to our Clients",
    "nosotros.subtitle": "Over 35 years evolving with quality as our goal",
    "nosotros.p1": "Founded over three decades ago as a family project, Central de Envasados has traveled a path of constant growth and technological reinvestment. What began as a local vision has today transformed into a European benchmark for high-capacity co-packing.",
    "nosotros.p2": "This evolution, based on continuous reinvestment and talent retention, has allowed us to scale without losing our essence: more than 250 specialized professionals daily manage critical operations from our more than 30 packaging rooms, 6 certified clean rooms and one sterile packaging room, and our own purified water plant for the manufacture of healthcare and cosmetic products.",
    "nosotros.p3": "Today, that same family essence —attention to detail, personalized treatment— coexists with the industrial rigor demanded by the world's most prestigious cosmetic and pharmaceutical firms. We are the invisible partner that ensures their quality reaches the final customer intact. That is our story: growing without forgetting that, in the end, each package bears the name of someone who trusts us.",
    "nosotros.cta": "Meet our team",
    "nosotros.stat1": "Sustained Growth",
    "nosotros.stat2": "Specialized Talent",
    "nosotros.stat3": "Technology Investment",
    "sectores.title": "Sectors",
    "sectores.subtitle": "Specialization by industry",
    "sectores.cosmetic.title": "Cosmetics, Hygiene & Perfumery",
    "sectores.cosmetic.description": "Strategic partner for the most prestigious firms in the sector. Specialists in packaging luxury fragrances and high-end cosmetics for world-leading brands.",
    "sectores.cosmetic.features": ["High-precision dedicated lines", "Quality control and continuous process monitoring", "Luxury component management"],
    "sectores.sanitary.title": "Sanitary Products",
    "sectores.sanitary.description": "Specialized infrastructure for the health sector. Strict compliance with international regulations for sanitary products.\nManufacturing area and sterile packaging.",
    "sectores.sanitary.features": ["6 Certified clean rooms + 1 Sterile Room", "Own purified water plant with 700 L/h capacity", "Continuous microbiological control"],
    "sectores.food.title": "Food",
    "sectores.food.description": "Advanced solutions for the food industry, with specific rooms for sensitive products requiring rigorous environmental control.",
    "sectores.food.features": ["Climate-controlled rooms with active humidity control", "Full traceability", "International food certifications"],
    "copacker.subtitle": "CO-PACKER - FULL SERVICE",
    "copacker.title": "Custom Packaging - 360º Projects",
    "copacker.description": "At Central de Envasados, we are not just a co-packer; we are your integral partner in project materialization, eliminating risks and managing every phase.",
    "copacker.cta.tech": "Our Technology",
    "copacker.cta.policy": "Management Policy",
    "copacker.feature1": "01. Industrial Infrastructure",
    "copacker.feature1.desc": "Scalable production capacity: We operate among the largest third-party packaging capacities in Europe, with 30 dedicated lines running simultaneously. This scale allows us to absorb seasonal demand peaks and maintain competitive response times without compromising quality.",
    "copacker.feature2": "02. Technological Versatility",
    "copacker.feature2.desc": "Multi-format, multi-sector: We have 30 differentiated packaging technologies (rotary, linear, flow-pack, labeling lines, etc.) that allow us to pivot between cosmetic, sanitary, and food formats without critical transition. One infrastructure, infinite configurations.",
    "copacker.feature3": "03. Controlled Environment",
    "copacker.feature3.desc": "Total certification and traceability: Manufacturing in sanitary areas and packaging in 6 certified Clean Rooms and one Sterile Packaging Room, with own purified water generation plant (700 L/h). We eliminate cross-contamination risks and guarantee batch traceability from raw material to final product.",
    "copacker.feature4": "04. Integrated Quality Control",
    "copacker.feature4.desc": "Zero defects on line: Continuous process inspection and control system, complemented by high-precision labeling and secondary packaging. Each package is verified before leaving the line.",
    "copacker.feature5": "05. Integral Packaging Management",
    "copacker.feature5.desc": "Real Full Service: Technical design and container sourcing, industrial graphic printing, and outer packaging management with a network of audited and certified collaborators. You bring the formula; we manage everything else.",
    "copacker.feature6": "06. Operational Partnership",
    "copacker.feature6.desc": "Your project, our team: Assignment of dedicated multidisciplinary teams per project (IQ, Production, Quality) that work as an extension of your operations department, not as an external provider.",
    "productos.title": "Products",
    "productos.subtitle": "Packaging solutions for every need",
    "productos.items.sachets.title": "Sachets & Wipes",
    "productos.items.sachets.description": "Ideal format for retail and sampling. Economical, versatile, customizable, and eco-friendly.",
    "productos.items.sachets.capacity": "0.1 ML - 100 ML",
    "productos.items.bottles.title": "Bottles",
    "productos.items.bottles.description": "The most versatile standard format. No limitations on format, capacity, or closure.",
    "productos.items.bottles.capacity": "0.5 ML - 1 LITER",
    "productos.items.jars.title": "Jars and Tubs",
    "productos.items.jars.description": "Maximum versatility for cosmetics and food. Wide range of capacities and finishes.",
    "productos.items.jars.capacity": "5 ML - 500 ML",
    "productos.items.vials.title": "Vials",
    "productos.items.vials.description": "Premium format for cosmetics and pharmacy. Wide variety of specialized closures.",
    "productos.items.vials.capacity": "1 ML - 30 ML",
    "instalaciones.title": "Facilities: Sanitary Grade Architecture",
    "instalaciones.subtitle": "Certified Industrial Capacity",
    "instalaciones.manufacturing.title": "Sanitary Grade Manufacturing",
    "instalaciones.manufacturing.description": "Critical formula development under aseptic protocols and total digital control.",
    "instalaciones.cleanrooms.title": "6 Certified Clean Rooms",
    "instalaciones.cleanrooms.description": "Qualified facilities for medical devices with continuous particle and microbiological control.",
    "instalaciones.food.title": "6 Specialized Food Rooms",
    "instalaciones.food.description": "Specific for gourmet food and nutraceuticals, with active humidity control.",
    "instalaciones.sterile.title": "Sterile Packaging Room",
    "instalaciones.sterile.description": "Area exclusively dedicated to packaging under strict aseptic conditions (Pharma Sector).",
    "instalaciones.water.title": "Purified Water Plant (700 L/h)",
    "instalaciones.water.description": "Quality assurance from the source. Autonomous supply for manufacturing and critical cleaning.",
    "instalaciones.warehouse.title": "Logistics with Total Traceability",
    "instalaciones.warehouse.description": "Comprehensive component management with clinical validation systems for each batch.",
    "instalaciones.stats.lines": "Production Lines",
    "instalaciones.stats.cleanrooms": "Clean Rooms",
    "instalaciones.stats.water": "L/h Purified Water",
    "instalaciones.stats.storage": "m² Warehouse",
    "calidad.title": "Regulatory Rigor and Full Spectrum Certifications",
    "calidad.subtitle": "Trust Guarantee for Leading Brands",
    "calidad.iso.title": "ISO 9001:2015",
    "calidad.iso.description": "Certified management system to ensure optimized processes and consistent results.",
    "calidad.gmp.title": "GMP (ISO 22716)",
    "calidad.gmp.description": "Strict compliance with Good Manufacturing Practices for medical and cosmetic products.",
    "calidad.process.title": "High-Precision Quality Control",
    "calidad.process.description": "We implement full digital traceability and clinical validation in every phase, ensuring each unit meets pharmaceutical purity standards.",
    "calidad.process.points": ["Microbiological validation in own lab", "100% visual inspection of finished products", "Full digital traceability for each batch", "Strict stability and airtightness control"],
    "contacto.title": "Contact",
    "contacto.subtitle": "Let's talk about your next project",
    "contacto.form.name": "Name",
    "contacto.form.email": "Email",
    "contacto.form.company": "Company",
    "contacto.form.phone": "Phone",
    "contacto.form.message": "Message",
    "contacto.form.submit": "Send message",
    "contacto.form.success": "Message sent successfully",
    "contacto.info.address": "Address",
    "contacto.info.phone": "Phone",
    "contacto.info.email": "Email",
    "contacto.info.schedule": "Schedule",
    "contacto.company.name": "Central de Envasados, S.A.",
    "contacto.company.address": "Polígono Industrial La Garena Sur, Miguel Servet, 10, 28806 Alcalá de Henares (Madrid)",
    "contacto.company.phone": "918 811 415",
    "contacto.company.email": "contacto@centralenvasados.com",
    "contacto.company.schedule": "Monday to Friday: 8:00 - 17:00",
    "footer.legalNotice": "In accordance with the provisions of Regulation (EU) 2016/679 of April 27, 2016 (GDPR), Organic Law 3/2018 of December 5 (LOPDGDD) and other current legal regulations on the protection of personal data, we inform you that the personal data provided in this contact form will be processed by Central de Envasados, S.A for the purpose of obtaining the selected catalog as well as managing your data with prior consent for the sending of commercial information. The legitimation for the processing of your personal data is based on the consent of the data subject. Your data will be kept for the time necessary to fulfill the purpose for which they were collected and to determine the possible responsibilities that could derive from said purpose and the processing of the data. No international data transfers, profiling or submission of data to automated decisions are carried out. You may exercise your rights of access, rectification, opposition, deletion, limitation of processing and portability by writing and with accreditation of your identity to Central de Envasados, S.A at the email address info@centraldeenvasados.com You have the right to file a claim with the control authority if you consider that your rights have not been correctly addressed, by contacting the Spanish Data Protection Agency (www.aepd.es).",
    "footer.rights": "All rights reserved",
    "footer.legal": "Legal Notice",
    "footer.privacy": "Privacy Policy",
    "footer.cookies": "Cookies"
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('es');

  const t = useCallback((key: string) => {
    return translations[language][key] || key;
  }, [language]);

  const toggleLanguage = useCallback(() => {
    setLanguage(prev => prev === 'es' ? 'en' : 'es');
  }, []);

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, toggleLanguage }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
